### PR TITLE
Convert fat arrows to property initializers

### PR DESCRIPTION
**Pull request by seth-outreach**
`decaffeinate` does not handle converting fat arrow functions very gracefully,
and we use them extensively in our CJSX components.  Previously it would bail
when trying to convert them.  This changes updates decaffeinate and overrides
one of its options to allow creating "invalid" constructors with binds prior to
`super()`, then converts those binds back into property initializers using
jscodeshift + react-codemod.

### CODE REVIEW

**Review by ghempton — APPROVED** [review]
LGTM, got some sample output?

**Comment by seth-outreach** [comment]
yup: https://github.com/getoutreach/outreach/pull/4755/commits/e1806e9871a470099fbed79117554b7645b09673

**Comment by ghempton** [comment]
Nice! Wonder if there is a way to get rid of the `initClass` as well.

**Comment by seth-outreach** [comment]
I've been thinking about that.  Now that there's an example of wiring in jscodeshift transforms, we could probably write some of our own.

**Pull request merged**
